- name: Set zsh as default
  user:
    name: "vagrant"
    shell: /usr/bin/zsh
- name: clone prezto
  git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: "/home/vagrant/.zprezto"
- name: Add symbolic link files
  file:
    src: "/home/vagrant/.zprezto/runcoms/{{item}}"
    dest: "/home/vagrant/.{{item}}"
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
- name: Customize zpreztorc
  blockinfile:
    path: "/home/vagrant/.zprezto/runcoms/zpreztorc"
    block: |
      'syntax-highlighting' \
      'docker' \
      'history-substring-search' \
      'autosuggestions'
- name: Customize zshrc
  blockinfile:
    path: "/home/vagrant/.zprezto/runcoms/zshrc"
    block: |
      fpath=(/usr/local/share/zsh-completions $fpath)
      AUTH_SOCK="${HOME}/.ssh-auth-sock"
      ln -snf "${SSH_AUTH_SOCK}" ${AUTH_SOCK} && export SSH_AUTH_SOCK=${AUTH_SOCK}
