- name: Install PHP
  apt:
    pkg:
      - unzip
      - php-cli
      - php-bcmath
      - php-xml
      - php-curl
      - php-gd
      - php-gmp
      - php-mysql
      - php-zip
      - php-mbstring
