- name: Check composer
  stat:
    path: /usr/local/bin/composer
  register: composer_bin
- block:
  - name: composer download
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer-installer
  - name: composer install
    shell: php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer
  - name: composer executable
    file:
      path: /usr/local/bin/composer
      mode: a+x
  when: not composer_bin.stat.exists
